#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCBCB082A1BB943DB (package-signing-key@mariadb.org)
#
Name     : mariadb
Version  : 10.9.2
Release  : 103
URL      : https://archive.mariadb.org/mariadb-10.9.2/source/mariadb-10.9.2.tar.gz
Source0  : https://archive.mariadb.org/mariadb-10.9.2/source/mariadb-10.9.2.tar.gz
Source1  : mariadb-install-db.service
Source2  : mariadb.service
Source3  : mariadb.tmpfiles
Source4  : https://archive.mariadb.org/mariadb-10.9.2/source/mariadb-10.9.2.tar.gz.asc
Summary  : Open source relational database
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause CC-BY-4.0 GPL-2.0 LGPL-2.1 OpenSSL
Requires: mariadb-extras-clientlib = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : bison
BuildRequires : bison-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : bzip2-dev
BuildRequires : curl-dev
BuildRequires : doxygen
BuildRequires : flex
BuildRequires : fmt-dev
BuildRequires : gflags-dev
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : gnutls-dev
BuildRequires : googletest-dev
BuildRequires : jemalloc-dev
BuildRequires : libaio-dev
BuildRequires : liburing-dev
BuildRequires : libxml2-dev
BuildRequires : lz4-dev
BuildRequires : ncurses-dev
BuildRequires : numactl-dev
BuildRequires : openjdk
BuildRequires : openjdk-dev
BuildRequires : openssl-dev
BuildRequires : pcre-dev
BuildRequires : pcre2-dev
BuildRequires : perl(Test::More)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(liblz4)
BuildRequires : pkgconfig(libssl)
BuildRequires : pkgconfig(libzstd)
BuildRequires : snappy-dev
BuildRequires : systemd-dev
BuildRequires : xz-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Change-default-bind-address-really-to-1-loopback-onl.patch
Patch2: 0002-Support-stateless-operation-by-migrating-to-usr-file.patch
Patch3: 0003-The-pam-moduledir-should-honor-PREFIX.patch
Patch4: 0004-Add-Runtime-Dependency-for-libssl-libcrypto.patch

%description
MariaDB is a community-developed, commercially supported fork of the MySQL
relational database management system, intended to remain free and open-source
software under the GNU General Public License.

%prep
%setup -q -n mariadb-10.9.2
cd %{_builddir}/mariadb-10.9.2
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672878439
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
%cmake .. -DBUILD_CONFIG=mysql_release \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DCMAKE_C_FLAGS="-fPIC $CFLAGS -fno-strict-aliasing -DBIG_JOINS=1 -fomit-frame-pointer" \
-DCMAKE_CXX_FLAGS="-fPIC $CXXFLAGS -fno-strict-aliasing -DBIG_JOINS=1 -felide-constructors" \
-DCMAKE_INSTALL_PREFIX=/usr \
-DCONNECT_WITH_REST=OFF \
-DENABLED_LOCAL_INFILE=ON \
-DINSTALL_DOCDIR="share/doc/mariadb" \
-DINSTALL_DOCREADMEDIR="share/doc/mariadb" \
-DINSTALL_INCLUDEDIR=include/mysql \
-DINSTALL_INFODIR=share/info \
-DINSTALL_LAYOUT=RPM \
-DINSTALL_LIBDIR="lib64" \
-DINSTALL_MANDIR=share/man \
-DINSTALL_MYSQLSHAREDIR=share/mariadb \
-DINSTALL_MYSQLTESTDIR=share/mysql-test \
-DINSTALL_PLUGINDIR="lib64/mysql/plugin" \
-DINSTALL_SBINDIR=sbin \
-DINSTALL_SCRIPTDIR=bin \
-DINSTALL_SHAREDIR=share/aclocal/mysql \
-DINSTALL_SUPPORTFILESDIR=share/mariadb \
-DINSTALL_SYSCONF2DIR="/usr/share/defaults/mariadb/my.cnf.d" \
-DINSTALL_SYSCONFDIR="/usr/share/defaults/mariadb" \
-DMYSQL_DATADIR="/var/lib/mysql" \
-DMYSQL_UNIX_ADDR=/run/mariadb/mariadb.sock \
-DTMPDIR=/var/tmp \
-DWITH_EMBEDDED_SERVER=ON \
-DWITH_JEMALLOC=no \
-DWITH_MYSQLD_LDFLAGS="-pie -Wl,-z,now" \
-DWITH_SSL=system \
-DWITH_ZLIB=system \
-DWITHOUT_MROONGA=True \
-DWITHOUT_TOKUDB=True \
-DWSREP_LIB_WITH_COVERAGE=OFF \
-DWITH_PCRE=system \
-DWITH_NUMA=On
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz -march=x86-64-v3 "
export FCFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz -march=x86-64-v3 "
export FFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz -march=x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz -march=x86-64-v3 "
export CFLAGS="$CFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
%cmake .. -DBUILD_CONFIG=mysql_release \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DCMAKE_C_FLAGS="-fPIC $CFLAGS -fno-strict-aliasing -DBIG_JOINS=1 -fomit-frame-pointer" \
-DCMAKE_CXX_FLAGS="-fPIC $CXXFLAGS -fno-strict-aliasing -DBIG_JOINS=1 -felide-constructors" \
-DCMAKE_INSTALL_PREFIX=/usr \
-DCONNECT_WITH_REST=OFF \
-DENABLED_LOCAL_INFILE=ON \
-DINSTALL_DOCDIR="share/doc/mariadb" \
-DINSTALL_DOCREADMEDIR="share/doc/mariadb" \
-DINSTALL_INCLUDEDIR=include/mysql \
-DINSTALL_INFODIR=share/info \
-DINSTALL_LAYOUT=RPM \
-DINSTALL_LIBDIR="lib64" \
-DINSTALL_MANDIR=share/man \
-DINSTALL_MYSQLSHAREDIR=share/mariadb \
-DINSTALL_MYSQLTESTDIR=share/mysql-test \
-DINSTALL_PLUGINDIR="lib64/mysql/plugin" \
-DINSTALL_SBINDIR=sbin \
-DINSTALL_SCRIPTDIR=bin \
-DINSTALL_SHAREDIR=share/aclocal/mysql \
-DINSTALL_SUPPORTFILESDIR=share/mariadb \
-DINSTALL_SYSCONF2DIR="/usr/share/defaults/mariadb/my.cnf.d" \
-DINSTALL_SYSCONFDIR="/usr/share/defaults/mariadb" \
-DMYSQL_DATADIR="/var/lib/mysql" \
-DMYSQL_UNIX_ADDR=/run/mariadb/mariadb.sock \
-DTMPDIR=/var/tmp \
-DWITH_EMBEDDED_SERVER=ON \
-DWITH_JEMALLOC=no \
-DWITH_MYSQLD_LDFLAGS="-pie -Wl,-z,now" \
-DWITH_SSL=system \
-DWITH_ZLIB=system \
-DWITHOUT_MROONGA=True \
-DWITHOUT_TOKUDB=True \
-DWSREP_LIB_WITH_COVERAGE=OFF \
-DWITH_PCRE=system \
-DWITH_NUMA=On
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pushd clr-build/mysql-test
./mtr --suite=unit --parallel=8 --mem
./mtr --suite=main --parallel=8 --mem --big-test || :
./mtr --suite=json --parallel=8 --mem || :
./mtr --suite=innodb --parallel=8 --mem || :
popd

%install
export SOURCE_DATE_EPOCH=1672878439
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mariadb
cp %{_builddir}/mariadb-%{version}/COPYING %{buildroot}/usr/share/package-licenses/mariadb/793d3cf202835b7b1584a2106d4292656d88e1ae || :
cp %{_builddir}/mariadb-%{version}/extra/readline/COPYING %{buildroot}/usr/share/package-licenses/mariadb/4231152540c27f86b02f96e73605e1ff18d2ee95 || :
cp %{_builddir}/mariadb-%{version}/extra/wolfssl/wolfssl/COPYING %{buildroot}/usr/share/package-licenses/mariadb/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/mariadb-%{version}/libmariadb/COPYING.LIB %{buildroot}/usr/share/package-licenses/mariadb/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/mariadb-%{version}/libmariadb/cmake/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/mariadb/ff3ed70db4739b3c6747c7f624fe2bad70802987 || :
cp %{_builddir}/mariadb-%{version}/plugin/handler_socket/handlersocket/COPYRIGHT.txt %{buildroot}/usr/share/package-licenses/mariadb/3914c2c16582bb3e404a22557a1f6b3c73db23a8 || :
cp %{_builddir}/mariadb-%{version}/plugin/handler_socket/libhsclient/COPYRIGHT.txt %{buildroot}/usr/share/package-licenses/mariadb/3914c2c16582bb3e404a22557a1f6b3c73db23a8 || :
cp %{_builddir}/mariadb-%{version}/plugin/handler_socket/perl-Net-HandlerSocket/COPYRIGHT.txt %{buildroot}/usr/share/package-licenses/mariadb/3914c2c16582bb3e404a22557a1f6b3c73db23a8 || :
cp %{_builddir}/mariadb-%{version}/plugin/server_audit/COPYING %{buildroot}/usr/share/package-licenses/mariadb/793d3cf202835b7b1584a2106d4292656d88e1ae || :
cp %{_builddir}/mariadb-%{version}/plugin/test_sql_service/COPYING %{buildroot}/usr/share/package-licenses/mariadb/793d3cf202835b7b1584a2106d4292656d88e1ae || :
cp %{_builddir}/mariadb-%{version}/scripts/sys_schema/COPYING %{buildroot}/usr/share/package-licenses/mariadb/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/mariadb-%{version}/scripts/sys_schema/LICENSE %{buildroot}/usr/share/package-licenses/mariadb/cdee1053a5302f5bd7ff2235a96d17c3c03ecd5c || :
cp %{_builddir}/mariadb-%{version}/storage/columnstore/columnstore/COPYING %{buildroot}/usr/share/package-licenses/mariadb/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1 || :
cp %{_builddir}/mariadb-%{version}/storage/columnstore/columnstore/LICENSE.md %{buildroot}/usr/share/package-licenses/mariadb/7ef0f1c84d9b22a046df5af1de92f44837236897 || :
cp %{_builddir}/mariadb-%{version}/storage/columnstore/columnstore/oam/oamcpp/COPYING %{buildroot}/usr/share/package-licenses/mariadb/b3aebbdebf056cbf1cb73b76edf8ea105c37239d || :
cp %{_builddir}/mariadb-%{version}/storage/columnstore/columnstore/utils/libmarias3/libmarias3/LICENSE %{buildroot}/usr/share/package-licenses/mariadb/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/mariadb-%{version}/storage/columnstore/columnstore/utils/libmarias3/libmarias3/debian/copyright %{buildroot}/usr/share/package-licenses/mariadb/46f1ac02159de45661948c23d007cf0ea989b459 || :
cp %{_builddir}/mariadb-%{version}/storage/columnstore/columnstore/utils/libmarias3/libmarias3/docs/introduction/license.rst %{buildroot}/usr/share/package-licenses/mariadb/040852207fc71d5144d9a73952f3c5b54003e89c || :
cp %{_builddir}/mariadb-%{version}/storage/innobase/COPYING.Google %{buildroot}/usr/share/package-licenses/mariadb/21c6e1c3c9ef7e68ec6cf63b3efda490e81ba26a || :
cp %{_builddir}/mariadb-%{version}/storage/innobase/COPYING.Percona %{buildroot}/usr/share/package-licenses/mariadb/8065fd50693d562d8f14d53ca84db13df5280c47 || :
cp %{_builddir}/mariadb-%{version}/storage/maria/libmarias3/LICENSE %{buildroot}/usr/share/package-licenses/mariadb/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/mariadb-%{version}/storage/maria/libmarias3/debian/copyright %{buildroot}/usr/share/package-licenses/mariadb/46f1ac02159de45661948c23d007cf0ea989b459 || :
cp %{_builddir}/mariadb-%{version}/storage/maria/libmarias3/docs/introduction/license.rst %{buildroot}/usr/share/package-licenses/mariadb/040852207fc71d5144d9a73952f3c5b54003e89c || :
cp %{_builddir}/mariadb-%{version}/storage/mroonga/COPYING %{buildroot}/usr/share/package-licenses/mariadb/d4c4fe8d1effe5471779e799caaa09cbb54e5b3f || :
cp %{_builddir}/mariadb-%{version}/storage/mroonga/vendor/groonga/COPYING %{buildroot}/usr/share/package-licenses/mariadb/5db84f12bde6c5e77125936e1470be0f400ece5f || :
cp %{_builddir}/mariadb-%{version}/storage/mroonga/vendor/groonga/vendor/plugins/groonga-normalizer-mysql/packages/debian/copyright %{buildroot}/usr/share/package-licenses/mariadb/60d021148ab131e6640e0edd7801f12f02a384e1 || :
cp %{_builddir}/mariadb-%{version}/storage/rocksdb/rocksdb/COPYING %{buildroot}/usr/share/package-licenses/mariadb/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/mariadb-%{version}/storage/rocksdb/rocksdb/LICENSE.Apache %{buildroot}/usr/share/package-licenses/mariadb/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/mariadb-%{version}/storage/rocksdb/rocksdb/LICENSE.leveldb %{buildroot}/usr/share/package-licenses/mariadb/59f297dcc2fbc8f9f3a966fd5290d72837fd6455 || :
cp %{_builddir}/mariadb-%{version}/storage/rocksdb/rocksdb/docs/LICENSE-DOCUMENTATION %{buildroot}/usr/share/package-licenses/mariadb/420cc096d9ce8dfabee4082196acb0383377f202 || :
cp %{_builddir}/mariadb-%{version}/vio/docs/COPYING.openssl %{buildroot}/usr/share/package-licenses/mariadb/7907ce0c0a371f3efe022b224eeebf5898f2bf8c || :
cp %{_builddir}/mariadb-%{version}/win/packaging/COPYING.rtf %{buildroot}/usr/share/package-licenses/mariadb/ebebbb6bb4a431d7099e28f3fd1817a2bfdb1f72 || :
cp %{_builddir}/mariadb-%{version}/wsrep-lib/COPYING %{buildroot}/usr/share/package-licenses/mariadb/47aad6f6cae3514cdd9b80bb32587bf81d3b1fc0 || :
cp %{_builddir}/mariadb-%{version}/wsrep-lib/LICENSE %{buildroot}/usr/share/package-licenses/mariadb/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/mariadb-%{version}/wsrep-lib/wsrep-API/v26/COPYING %{buildroot}/usr/share/package-licenses/mariadb/4cc77b90af91e615a64ae04893fdffa7939db84c || :
pushd clr-build-avx2
%make_install_v3  || :
popd
pushd clr-build
%make_install
popd
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/mariadb-install-db.service
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/systemd/system/mariadb.service
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE3} %{buildroot}/usr/lib/tmpfiles.d/mariadb.conf
## Remove excluded files
rm -f %{buildroot}*/usr/bin/rcmysql
## install_append content
rm -rf %{buildroot}*/usr/share/mysql-test
mkdir -p %{buildroot}/usr/share/mariadb
mkdir -p %{buildroot}-v3/usr/share/mariadb
mv %{buildroot}/usr/bin/wsrep_sst_common %{buildroot}/usr/share/mariadb/
mv %{buildroot}-v3/usr/bin/wsrep_sst_common %{buildroot}-v3/usr/share/mariadb/
ln -s ../share/mariadb/wsrep_sst_common %{buildroot}/usr/bin/wsrep_sst_common
chmod -s %{buildroot}*/usr/lib64/mysql/plugin/auth_pam_tool_dir/auth_pam_tool
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
