#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCBCB082A1BB943DB (package-signing-key@mariadb.org)
#
Name     : mariadb
Version  : 10.6.8
Release  : 99
URL      : https://ftp.osuosl.org/pub/mariadb/mariadb-10.6.8/source/mariadb-10.6.8.tar.gz
Source0  : https://ftp.osuosl.org/pub/mariadb/mariadb-10.6.8/source/mariadb-10.6.8.tar.gz
Source1  : mariadb-install-db.service
Source2  : mariadb.service
Source3  : mariadb.tmpfiles
Source4  : https://ftp.osuosl.org/pub/mariadb/mariadb-10.6.8/source/mariadb-10.6.8.tar.gz.asc
Summary  : Open source relational database
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause CC-BY-4.0 GPL-2.0 LGPL-2.1 OpenSSL
Requires: mariadb-bin = %{version}-%{release}
Requires: mariadb-config = %{version}-%{release}
Requires: mariadb-data = %{version}-%{release}
Requires: mariadb-filemap = %{version}-%{release}
Requires: mariadb-lib = %{version}-%{release}
Requires: mariadb-license = %{version}-%{release}
Requires: mariadb-man = %{version}-%{release}
Requires: mariadb-services = %{version}-%{release}
Requires: mariadb-extras-clientlib = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : bison
BuildRequires : bison-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : bzip2-dev
BuildRequires : curl-dev
BuildRequires : doxygen
BuildRequires : flex
BuildRequires : gflags-dev
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : gnutls-dev
BuildRequires : googletest-dev
BuildRequires : jemalloc-dev
BuildRequires : libaio-dev
BuildRequires : liburing-dev
BuildRequires : libxml2-dev
BuildRequires : lz4-dev
BuildRequires : ncurses-dev
BuildRequires : numactl-dev
BuildRequires : openjdk
BuildRequires : openjdk-dev
BuildRequires : openssl-dev
BuildRequires : pcre-dev
BuildRequires : pcre2-dev
BuildRequires : perl(Test::More)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(liblz4)
BuildRequires : pkgconfig(libssl)
BuildRequires : pkgconfig(libzstd)
BuildRequires : snappy-dev
BuildRequires : systemd-dev
BuildRequires : xz-dev
BuildRequires : zlib-dev
Patch1: 0001-Change-default-bind-address-really-to-1-loopback-onl.patch
Patch2: 0002-Support-stateless-operation-by-migrating-to-usr-file.patch
Patch3: 0003-The-pam-moduledir-should-honor-PREFIX.patch
Patch4: 0004-Add-Runtime-Dependency-for-libssl-libcrypto.patch

%description
MariaDB is a community-developed, commercially supported fork of the MySQL
relational database management system, intended to remain free and open-source
software under the GNU General Public License.

%package bin
Summary: bin components for the mariadb package.
Group: Binaries
Requires: mariadb-data = %{version}-%{release}
Requires: mariadb-config = %{version}-%{release}
Requires: mariadb-license = %{version}-%{release}
Requires: mariadb-services = %{version}-%{release}
Requires: mariadb-filemap = %{version}-%{release}

%description bin
bin components for the mariadb package.


%package config
Summary: config components for the mariadb package.
Group: Default

%description config
config components for the mariadb package.


%package data
Summary: data components for the mariadb package.
Group: Data

%description data
data components for the mariadb package.


%package dev
Summary: dev components for the mariadb package.
Group: Development
Requires: mariadb-lib = %{version}-%{release}
Requires: mariadb-bin = %{version}-%{release}
Requires: mariadb-data = %{version}-%{release}
Provides: mariadb-devel = %{version}-%{release}
Requires: mariadb = %{version}-%{release}

%description dev
dev components for the mariadb package.


%package doc
Summary: doc components for the mariadb package.
Group: Documentation
Requires: mariadb-man = %{version}-%{release}

%description doc
doc components for the mariadb package.


%package extras
Summary: extras components for the mariadb package.
Group: Default

%description extras
extras components for the mariadb package.


%package extras-clientlib
Summary: extras-clientlib components for the mariadb package.
Group: Default

%description extras-clientlib
extras-clientlib components for the mariadb package.


%package filemap
Summary: filemap components for the mariadb package.
Group: Default

%description filemap
filemap components for the mariadb package.


%package lib
Summary: lib components for the mariadb package.
Group: Libraries
Requires: mariadb-data = %{version}-%{release}
Requires: mariadb-license = %{version}-%{release}
Requires: mariadb-filemap = %{version}-%{release}

%description lib
lib components for the mariadb package.


%package license
Summary: license components for the mariadb package.
Group: Default

%description license
license components for the mariadb package.


%package man
Summary: man components for the mariadb package.
Group: Default

%description man
man components for the mariadb package.


%package services
Summary: services components for the mariadb package.
Group: Systemd services

%description services
services components for the mariadb package.


%prep
%setup -q -n mariadb-10.6.8
cd %{_builddir}/mariadb-10.6.8
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656372109
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DBUILD_CONFIG=mysql_release \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DCMAKE_C_FLAGS="-fPIC $CFLAGS -fno-strict-aliasing -DBIG_JOINS=1 -fomit-frame-pointer" \
-DCMAKE_CXX_FLAGS="-fPIC $CXXFLAGS -fno-strict-aliasing -DBIG_JOINS=1 -felide-constructors" \
-DCMAKE_INSTALL_PREFIX=/usr \
-DCONNECT_WITH_REST=OFF \
-DENABLED_LOCAL_INFILE=ON \
-DINSTALL_DOCDIR="share/doc/mariadb" \
-DINSTALL_DOCREADMEDIR="share/doc/mariadb" \
-DINSTALL_INCLUDEDIR=include/mysql \
-DINSTALL_INFODIR=share/info \
-DINSTALL_LAYOUT=RPM \
-DINSTALL_LIBDIR="lib64" \
-DINSTALL_MANDIR=share/man \
-DINSTALL_MYSQLSHAREDIR=share/mariadb \
-DINSTALL_MYSQLTESTDIR=share/mysql-test \
-DINSTALL_PLUGINDIR="lib64/mysql/plugin" \
-DINSTALL_SBINDIR=sbin \
-DINSTALL_SCRIPTDIR=bin \
-DINSTALL_SHAREDIR=share/aclocal/mysql \
-DINSTALL_SUPPORTFILESDIR=share/mariadb \
-DINSTALL_SYSCONF2DIR="/usr/share/defaults/mariadb/my.cnf.d" \
-DINSTALL_SYSCONFDIR="/usr/share/defaults/mariadb" \
-DMYSQL_DATADIR="/var/lib/mysql" \
-DMYSQL_UNIX_ADDR=/run/mariadb/mariadb.sock \
-DTMPDIR=/var/tmp \
-DWITH_EMBEDDED_SERVER=ON \
-DWITH_JEMALLOC=no \
-DWITH_MYSQLD_LDFLAGS="-pie -Wl,-z,now" \
-DWITH_SSL=system \
-DWITH_ZLIB=system \
-DWITHOUT_MROONGA=True \
-DWITHOUT_TOKUDB=True \
-DWSREP_LIB_WITH_COVERAGE=OFF \
-DWITH_PCRE=system \
-DWITH_NUMA=On
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -O3 -Wl,-z,x86-64-v3 -fno-lto -march=x86-64-v3 -msse2avx -mtune=skylake "
export FCFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v3 -fno-lto -march=x86-64-v3 -msse2avx -mtune=skylake "
export FFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v3 -fno-lto -march=x86-64-v3 -msse2avx -mtune=skylake "
export CXXFLAGS="$CXXFLAGS -O3 -Wl,-z,x86-64-v3 -fno-lto -march=x86-64-v3 -msse2avx -mtune=skylake "
export CFLAGS="$CFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
%cmake .. -DBUILD_CONFIG=mysql_release \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DCMAKE_C_FLAGS="-fPIC $CFLAGS -fno-strict-aliasing -DBIG_JOINS=1 -fomit-frame-pointer" \
-DCMAKE_CXX_FLAGS="-fPIC $CXXFLAGS -fno-strict-aliasing -DBIG_JOINS=1 -felide-constructors" \
-DCMAKE_INSTALL_PREFIX=/usr \
-DCONNECT_WITH_REST=OFF \
-DENABLED_LOCAL_INFILE=ON \
-DINSTALL_DOCDIR="share/doc/mariadb" \
-DINSTALL_DOCREADMEDIR="share/doc/mariadb" \
-DINSTALL_INCLUDEDIR=include/mysql \
-DINSTALL_INFODIR=share/info \
-DINSTALL_LAYOUT=RPM \
-DINSTALL_LIBDIR="lib64" \
-DINSTALL_MANDIR=share/man \
-DINSTALL_MYSQLSHAREDIR=share/mariadb \
-DINSTALL_MYSQLTESTDIR=share/mysql-test \
-DINSTALL_PLUGINDIR="lib64/mysql/plugin" \
-DINSTALL_SBINDIR=sbin \
-DINSTALL_SCRIPTDIR=bin \
-DINSTALL_SHAREDIR=share/aclocal/mysql \
-DINSTALL_SUPPORTFILESDIR=share/mariadb \
-DINSTALL_SYSCONF2DIR="/usr/share/defaults/mariadb/my.cnf.d" \
-DINSTALL_SYSCONFDIR="/usr/share/defaults/mariadb" \
-DMYSQL_DATADIR="/var/lib/mysql" \
-DMYSQL_UNIX_ADDR=/run/mariadb/mariadb.sock \
-DTMPDIR=/var/tmp \
-DWITH_EMBEDDED_SERVER=ON \
-DWITH_JEMALLOC=no \
-DWITH_MYSQLD_LDFLAGS="-pie -Wl,-z,now" \
-DWITH_SSL=system \
-DWITH_ZLIB=system \
-DWITHOUT_MROONGA=True \
-DWITHOUT_TOKUDB=True \
-DWSREP_LIB_WITH_COVERAGE=OFF \
-DWITH_PCRE=system \
-DWITH_NUMA=On
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pushd clr-build/mysql-test
./mtr --suite=unit --parallel=8 --mem
./mtr --suite=main --parallel=8 --mem --big-test || :
./mtr --suite=json --parallel=8 --mem || :
./mtr --suite=innodb --parallel=8 --mem || :
popd

%install
export SOURCE_DATE_EPOCH=1656372109
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mariadb
cp %{_builddir}/mariadb-10.6.8/COPYING %{buildroot}/usr/share/package-licenses/mariadb/793d3cf202835b7b1584a2106d4292656d88e1ae
cp %{_builddir}/mariadb-10.6.8/extra/readline/COPYING %{buildroot}/usr/share/package-licenses/mariadb/4231152540c27f86b02f96e73605e1ff18d2ee95
cp %{_builddir}/mariadb-10.6.8/extra/wolfssl/wolfssl/COPYING %{buildroot}/usr/share/package-licenses/mariadb/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/mariadb-10.6.8/libmariadb/COPYING.LIB %{buildroot}/usr/share/package-licenses/mariadb/01a6b4bf79aca9b556822601186afab86e8c4fbf
cp %{_builddir}/mariadb-10.6.8/libmariadb/cmake/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/mariadb/ff3ed70db4739b3c6747c7f624fe2bad70802987
cp %{_builddir}/mariadb-10.6.8/plugin/handler_socket/handlersocket/COPYRIGHT.txt %{buildroot}/usr/share/package-licenses/mariadb/3914c2c16582bb3e404a22557a1f6b3c73db23a8
cp %{_builddir}/mariadb-10.6.8/plugin/handler_socket/libhsclient/COPYRIGHT.txt %{buildroot}/usr/share/package-licenses/mariadb/3914c2c16582bb3e404a22557a1f6b3c73db23a8
cp %{_builddir}/mariadb-10.6.8/plugin/handler_socket/perl-Net-HandlerSocket/COPYRIGHT.txt %{buildroot}/usr/share/package-licenses/mariadb/3914c2c16582bb3e404a22557a1f6b3c73db23a8
cp %{_builddir}/mariadb-10.6.8/plugin/server_audit/COPYING %{buildroot}/usr/share/package-licenses/mariadb/793d3cf202835b7b1584a2106d4292656d88e1ae
cp %{_builddir}/mariadb-10.6.8/plugin/test_sql_service/COPYING %{buildroot}/usr/share/package-licenses/mariadb/793d3cf202835b7b1584a2106d4292656d88e1ae
cp %{_builddir}/mariadb-10.6.8/scripts/sys_schema/COPYING %{buildroot}/usr/share/package-licenses/mariadb/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
cp %{_builddir}/mariadb-10.6.8/scripts/sys_schema/LICENSE %{buildroot}/usr/share/package-licenses/mariadb/cdee1053a5302f5bd7ff2235a96d17c3c03ecd5c
cp %{_builddir}/mariadb-10.6.8/storage/columnstore/columnstore/COPYING %{buildroot}/usr/share/package-licenses/mariadb/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1
cp %{_builddir}/mariadb-10.6.8/storage/columnstore/columnstore/LICENSE.md %{buildroot}/usr/share/package-licenses/mariadb/7ef0f1c84d9b22a046df5af1de92f44837236897
cp %{_builddir}/mariadb-10.6.8/storage/columnstore/columnstore/oam/oamcpp/COPYING %{buildroot}/usr/share/package-licenses/mariadb/b3aebbdebf056cbf1cb73b76edf8ea105c37239d
cp %{_builddir}/mariadb-10.6.8/storage/columnstore/columnstore/utils/libmarias3/libmarias3/LICENSE %{buildroot}/usr/share/package-licenses/mariadb/01a6b4bf79aca9b556822601186afab86e8c4fbf
cp %{_builddir}/mariadb-10.6.8/storage/columnstore/columnstore/utils/libmarias3/libmarias3/debian/copyright %{buildroot}/usr/share/package-licenses/mariadb/46f1ac02159de45661948c23d007cf0ea989b459
cp %{_builddir}/mariadb-10.6.8/storage/columnstore/columnstore/utils/libmarias3/libmarias3/docs/introduction/license.rst %{buildroot}/usr/share/package-licenses/mariadb/040852207fc71d5144d9a73952f3c5b54003e89c
cp %{_builddir}/mariadb-10.6.8/storage/innobase/COPYING.Google %{buildroot}/usr/share/package-licenses/mariadb/21c6e1c3c9ef7e68ec6cf63b3efda490e81ba26a
cp %{_builddir}/mariadb-10.6.8/storage/innobase/COPYING.Percona %{buildroot}/usr/share/package-licenses/mariadb/8065fd50693d562d8f14d53ca84db13df5280c47
cp %{_builddir}/mariadb-10.6.8/storage/maria/libmarias3/LICENSE %{buildroot}/usr/share/package-licenses/mariadb/01a6b4bf79aca9b556822601186afab86e8c4fbf
cp %{_builddir}/mariadb-10.6.8/storage/maria/libmarias3/debian/copyright %{buildroot}/usr/share/package-licenses/mariadb/46f1ac02159de45661948c23d007cf0ea989b459
cp %{_builddir}/mariadb-10.6.8/storage/maria/libmarias3/docs/introduction/license.rst %{buildroot}/usr/share/package-licenses/mariadb/040852207fc71d5144d9a73952f3c5b54003e89c
cp %{_builddir}/mariadb-10.6.8/storage/mroonga/COPYING %{buildroot}/usr/share/package-licenses/mariadb/d4c4fe8d1effe5471779e799caaa09cbb54e5b3f
cp %{_builddir}/mariadb-10.6.8/storage/mroonga/vendor/groonga/COPYING %{buildroot}/usr/share/package-licenses/mariadb/5db84f12bde6c5e77125936e1470be0f400ece5f
cp %{_builddir}/mariadb-10.6.8/storage/mroonga/vendor/groonga/vendor/plugins/groonga-normalizer-mysql/packages/debian/copyright %{buildroot}/usr/share/package-licenses/mariadb/60d021148ab131e6640e0edd7801f12f02a384e1
cp %{_builddir}/mariadb-10.6.8/storage/rocksdb/rocksdb/COPYING %{buildroot}/usr/share/package-licenses/mariadb/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/mariadb-10.6.8/storage/rocksdb/rocksdb/LICENSE.Apache %{buildroot}/usr/share/package-licenses/mariadb/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/mariadb-10.6.8/storage/rocksdb/rocksdb/LICENSE.leveldb %{buildroot}/usr/share/package-licenses/mariadb/59f297dcc2fbc8f9f3a966fd5290d72837fd6455
cp %{_builddir}/mariadb-10.6.8/storage/rocksdb/rocksdb/docs/LICENSE-DOCUMENTATION %{buildroot}/usr/share/package-licenses/mariadb/420cc096d9ce8dfabee4082196acb0383377f202
cp %{_builddir}/mariadb-10.6.8/vio/docs/COPYING.openssl %{buildroot}/usr/share/package-licenses/mariadb/7907ce0c0a371f3efe022b224eeebf5898f2bf8c
cp %{_builddir}/mariadb-10.6.8/win/packaging/COPYING.rtf %{buildroot}/usr/share/package-licenses/mariadb/ebebbb6bb4a431d7099e28f3fd1817a2bfdb1f72
cp %{_builddir}/mariadb-10.6.8/wsrep-lib/COPYING %{buildroot}/usr/share/package-licenses/mariadb/47aad6f6cae3514cdd9b80bb32587bf81d3b1fc0
cp %{_builddir}/mariadb-10.6.8/wsrep-lib/LICENSE %{buildroot}/usr/share/package-licenses/mariadb/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/mariadb-10.6.8/wsrep-lib/wsrep-API/v26/COPYING %{buildroot}/usr/share/package-licenses/mariadb/4cc77b90af91e615a64ae04893fdffa7939db84c
pushd clr-build-avx2
%make_install_v3  || :
popd
pushd clr-build
%make_install
popd
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/mariadb-install-db.service
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/systemd/system/mariadb.service
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE3} %{buildroot}/usr/lib/tmpfiles.d/mariadb.conf
## Remove excluded files
rm -f %{buildroot}*/usr/bin/rcmysql
## install_append content
rm -rf %{buildroot}*/usr/share/mysql-test
mkdir -p %{buildroot}/usr/share/mariadb
mkdir -p %{buildroot}-v3/usr/share/mariadb
mv %{buildroot}/usr/bin/wsrep_sst_common %{buildroot}/usr/share/mariadb/
mv %{buildroot}-v3/usr/bin/wsrep_sst_common %{buildroot}-v3/usr/share/mariadb/
ln -s ../share/mariadb/wsrep_sst_common %{buildroot}/usr/bin/wsrep_sst_common
chmod -s %{buildroot}*/usr/lib64/mysql/plugin/auth_pam_tool_dir/auth_pam_tool
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/mysql/plugin/auth_pam_tool_dir/auth_pam_tool
/usr/lib64/mysql/plugin/daemon_example.ini

%files bin
%defattr(-,root,root,-)
/usr/bin/aria_chk
/usr/bin/aria_dump_log
/usr/bin/aria_ftdump
/usr/bin/aria_pack
/usr/bin/aria_read_log
/usr/bin/aria_s3_copy
/usr/bin/galera_new_cluster
/usr/bin/galera_recovery
/usr/bin/innochecksum
/usr/bin/mariabackup
/usr/bin/mariadb
/usr/bin/mariadb-access
/usr/bin/mariadb-admin
/usr/bin/mariadb-backup
/usr/bin/mariadb-binlog
/usr/bin/mariadb-check
/usr/bin/mariadb-client-test
/usr/bin/mariadb-config
/usr/bin/mariadb-conv
/usr/bin/mariadb-convert-table-format
/usr/bin/mariadb-dump
/usr/bin/mariadb-dumpslow
/usr/bin/mariadb-find-rows
/usr/bin/mariadb-fix-extensions
/usr/bin/mariadb-hotcopy
/usr/bin/mariadb-import
/usr/bin/mariadb-install-db
/usr/bin/mariadb-ldb
/usr/bin/mariadb-plugin
/usr/bin/mariadb-secure-installation
/usr/bin/mariadb-service-convert
/usr/bin/mariadb-setpermission
/usr/bin/mariadb-show
/usr/bin/mariadb-slap
/usr/bin/mariadb-test
/usr/bin/mariadb-tzinfo-to-sql
/usr/bin/mariadb-upgrade
/usr/bin/mariadb-waitpid
/usr/bin/mariadb_config
/usr/bin/mariadbd
/usr/bin/mariadbd-multi
/usr/bin/mariadbd-safe
/usr/bin/mariadbd-safe-helper
/usr/bin/mbstream
/usr/bin/msql2mysql
/usr/bin/my_print_defaults
/usr/bin/myisam_ftdump
/usr/bin/myisamchk
/usr/bin/myisamlog
/usr/bin/myisampack
/usr/bin/myrocks_hotbackup
/usr/bin/mysql
/usr/bin/mysql_client_test
/usr/bin/mysql_config
/usr/bin/mysql_convert_table_format
/usr/bin/mysql_find_rows
/usr/bin/mysql_fix_extensions
/usr/bin/mysql_install_db
/usr/bin/mysql_ldb
/usr/bin/mysql_plugin
/usr/bin/mysql_secure_installation
/usr/bin/mysql_setpermission
/usr/bin/mysql_tzinfo_to_sql
/usr/bin/mysql_upgrade
/usr/bin/mysql_waitpid
/usr/bin/mysqlaccess
/usr/bin/mysqladmin
/usr/bin/mysqlbinlog
/usr/bin/mysqlcheck
/usr/bin/mysqld
/usr/bin/mysqld_multi
/usr/bin/mysqld_safe
/usr/bin/mysqld_safe_helper
/usr/bin/mysqldump
/usr/bin/mysqldumpslow
/usr/bin/mysqlhotcopy
/usr/bin/mysqlimport
/usr/bin/mysqlshow
/usr/bin/mysqlslap
/usr/bin/mysqltest
/usr/bin/mytop
/usr/bin/perror
/usr/bin/replace
/usr/bin/resolve_stack_dump
/usr/bin/resolveip
/usr/bin/sst_dump
/usr/bin/test-connect-t
/usr/bin/wsrep_sst_backup
/usr/bin/wsrep_sst_common
/usr/bin/wsrep_sst_mariabackup
/usr/bin/wsrep_sst_mysqldump
/usr/bin/wsrep_sst_rsync
/usr/bin/wsrep_sst_rsync_wan
/usr/share/clear/optimized-elf/bin*

%files config
%defattr(-,root,root,-)
/usr/lib/sysusers.d/mariadb.conf
/usr/lib/tmpfiles.d/mariadb.conf

%files data
%defattr(-,root,root,-)
/usr/share/aclocal/mysql/aclocal/mysql.m4
/usr/share/defaults/mariadb/logrotate.d/mysql
/usr/share/defaults/mariadb/my.cnf
/usr/share/defaults/mariadb/my.cnf.d/client.cnf
/usr/share/defaults/mariadb/my.cnf.d/enable_encryption.preset
/usr/share/defaults/mariadb/my.cnf.d/mysql-clients.cnf
/usr/share/defaults/mariadb/my.cnf.d/s3.cnf
/usr/share/defaults/mariadb/my.cnf.d/server.cnf
/usr/share/defaults/mariadb/my.cnf.d/spider.cnf
/usr/share/mariadb/binary-configure
/usr/share/mariadb/bulgarian/errmsg.sys
/usr/share/mariadb/charsets/Index.xml
/usr/share/mariadb/charsets/README
/usr/share/mariadb/charsets/armscii8.xml
/usr/share/mariadb/charsets/ascii.xml
/usr/share/mariadb/charsets/cp1250.xml
/usr/share/mariadb/charsets/cp1251.xml
/usr/share/mariadb/charsets/cp1256.xml
/usr/share/mariadb/charsets/cp1257.xml
/usr/share/mariadb/charsets/cp850.xml
/usr/share/mariadb/charsets/cp852.xml
/usr/share/mariadb/charsets/cp866.xml
/usr/share/mariadb/charsets/dec8.xml
/usr/share/mariadb/charsets/geostd8.xml
/usr/share/mariadb/charsets/greek.xml
/usr/share/mariadb/charsets/hebrew.xml
/usr/share/mariadb/charsets/hp8.xml
/usr/share/mariadb/charsets/keybcs2.xml
/usr/share/mariadb/charsets/koi8r.xml
/usr/share/mariadb/charsets/koi8u.xml
/usr/share/mariadb/charsets/latin1.xml
/usr/share/mariadb/charsets/latin2.xml
/usr/share/mariadb/charsets/latin5.xml
/usr/share/mariadb/charsets/latin7.xml
/usr/share/mariadb/charsets/macce.xml
/usr/share/mariadb/charsets/macroman.xml
/usr/share/mariadb/charsets/swe7.xml
/usr/share/mariadb/chinese/errmsg.sys
/usr/share/mariadb/czech/errmsg.sys
/usr/share/mariadb/danish/errmsg.sys
/usr/share/mariadb/dutch/errmsg.sys
/usr/share/mariadb/english/errmsg.sys
/usr/share/mariadb/errmsg-utf8.txt
/usr/share/mariadb/estonian/errmsg.sys
/usr/share/mariadb/fill_help_tables.sql
/usr/share/mariadb/french/errmsg.sys
/usr/share/mariadb/german/errmsg.sys
/usr/share/mariadb/greek/errmsg.sys
/usr/share/mariadb/hindi/errmsg.sys
/usr/share/mariadb/hungarian/errmsg.sys
/usr/share/mariadb/italian/errmsg.sys
/usr/share/mariadb/japanese/errmsg.sys
/usr/share/mariadb/korean/errmsg.sys
/usr/share/mariadb/magic
/usr/share/mariadb/maria_add_gis_sp.sql
/usr/share/mariadb/maria_add_gis_sp_bootstrap.sql
/usr/share/mariadb/mysql-log-rotate
/usr/share/mariadb/mysql.server
/usr/share/mariadb/mysql_performance_tables.sql
/usr/share/mariadb/mysql_sys_schema.sql
/usr/share/mariadb/mysql_system_tables.sql
/usr/share/mariadb/mysql_system_tables_data.sql
/usr/share/mariadb/mysql_test_data_timezone.sql
/usr/share/mariadb/mysql_test_db.sql
/usr/share/mariadb/mysqld_multi.server
/usr/share/mariadb/norwegian-ny/errmsg.sys
/usr/share/mariadb/norwegian/errmsg.sys
/usr/share/mariadb/policy/apparmor/README
/usr/share/mariadb/policy/apparmor/usr.sbin.mysqld
/usr/share/mariadb/policy/apparmor/usr.sbin.mysqld.local
/usr/share/mariadb/policy/selinux/README
/usr/share/mariadb/policy/selinux/mariadb-server.fc
/usr/share/mariadb/policy/selinux/mariadb-server.te
/usr/share/mariadb/policy/selinux/mariadb.te
/usr/share/mariadb/polish/errmsg.sys
/usr/share/mariadb/portuguese/errmsg.sys
/usr/share/mariadb/romanian/errmsg.sys
/usr/share/mariadb/russian/errmsg.sys
/usr/share/mariadb/serbian/errmsg.sys
/usr/share/mariadb/slovak/errmsg.sys
/usr/share/mariadb/spanish/errmsg.sys
/usr/share/mariadb/swedish/errmsg.sys
/usr/share/mariadb/systemd/mariadb-extra@.socket
/usr/share/mariadb/systemd/mariadb.service
/usr/share/mariadb/systemd/mariadb@.service
/usr/share/mariadb/systemd/mariadb@.socket
/usr/share/mariadb/systemd/mysql.service
/usr/share/mariadb/systemd/mysqld.service
/usr/share/mariadb/systemd/use_galera_new_cluster.conf
/usr/share/mariadb/ukrainian/errmsg.sys
/usr/share/mariadb/wsrep.cnf
/usr/share/mariadb/wsrep_notify
/usr/share/mariadb/wsrep_sst_common

%files dev
%defattr(-,root,root,-)
/usr/include/mysql/errmsg.h
/usr/include/mysql/ma_list.h
/usr/include/mysql/ma_pvio.h
/usr/include/mysql/ma_tls.h
/usr/include/mysql/mariadb/ma_io.h
/usr/include/mysql/mariadb_com.h
/usr/include/mysql/mariadb_ctype.h
/usr/include/mysql/mariadb_dyncol.h
/usr/include/mysql/mariadb_rpl.h
/usr/include/mysql/mariadb_stmt.h
/usr/include/mysql/mariadb_version.h
/usr/include/mysql/my_config.h
/usr/include/mysql/my_global.h
/usr/include/mysql/my_sys.h
/usr/include/mysql/mysql.h
/usr/include/mysql/mysql/client_plugin.h
/usr/include/mysql/mysql/plugin_auth.h
/usr/include/mysql/mysql/plugin_auth_common.h
/usr/include/mysql/mysql_com.h
/usr/include/mysql/mysql_version.h
/usr/include/mysql/mysqld_error.h
/usr/include/mysql/server/big_endian.h
/usr/include/mysql/server/byte_order_generic.h
/usr/include/mysql/server/byte_order_generic_x86.h
/usr/include/mysql/server/byte_order_generic_x86_64.h
/usr/include/mysql/server/decimal.h
/usr/include/mysql/server/errmsg.h
/usr/include/mysql/server/handler_ername.h
/usr/include/mysql/server/handler_state.h
/usr/include/mysql/server/json_lib.h
/usr/include/mysql/server/keycache.h
/usr/include/mysql/server/little_endian.h
/usr/include/mysql/server/m_ctype.h
/usr/include/mysql/server/m_string.h
/usr/include/mysql/server/ma_dyncol.h
/usr/include/mysql/server/my_alloc.h
/usr/include/mysql/server/my_attribute.h
/usr/include/mysql/server/my_byteorder.h
/usr/include/mysql/server/my_compiler.h
/usr/include/mysql/server/my_config.h
/usr/include/mysql/server/my_dbug.h
/usr/include/mysql/server/my_decimal_limits.h
/usr/include/mysql/server/my_dir.h
/usr/include/mysql/server/my_getopt.h
/usr/include/mysql/server/my_global.h
/usr/include/mysql/server/my_list.h
/usr/include/mysql/server/my_net.h
/usr/include/mysql/server/my_pthread.h
/usr/include/mysql/server/my_sys.h
/usr/include/mysql/server/my_valgrind.h
/usr/include/mysql/server/my_xml.h
/usr/include/mysql/server/mysql.h
/usr/include/mysql/server/mysql/auth_dialog_client.h
/usr/include/mysql/server/mysql/client_plugin.h
/usr/include/mysql/server/mysql/plugin.h
/usr/include/mysql/server/mysql/plugin_audit.h
/usr/include/mysql/server/mysql/plugin_auth.h
/usr/include/mysql/server/mysql/plugin_auth_common.h
/usr/include/mysql/server/mysql/plugin_data_type.h
/usr/include/mysql/server/mysql/plugin_encryption.h
/usr/include/mysql/server/mysql/plugin_ftparser.h
/usr/include/mysql/server/mysql/plugin_function.h
/usr/include/mysql/server/mysql/plugin_password_validation.h
/usr/include/mysql/server/mysql/psi/mysql_file.h
/usr/include/mysql/server/mysql/psi/mysql_idle.h
/usr/include/mysql/server/mysql/psi/mysql_mdl.h
/usr/include/mysql/server/mysql/psi/mysql_memory.h
/usr/include/mysql/server/mysql/psi/mysql_ps.h
/usr/include/mysql/server/mysql/psi/mysql_socket.h
/usr/include/mysql/server/mysql/psi/mysql_sp.h
/usr/include/mysql/server/mysql/psi/mysql_stage.h
/usr/include/mysql/server/mysql/psi/mysql_statement.h
/usr/include/mysql/server/mysql/psi/mysql_table.h
/usr/include/mysql/server/mysql/psi/mysql_thread.h
/usr/include/mysql/server/mysql/psi/mysql_transaction.h
/usr/include/mysql/server/mysql/psi/psi.h
/usr/include/mysql/server/mysql/psi/psi_abi_v0.h
/usr/include/mysql/server/mysql/psi/psi_abi_v1.h
/usr/include/mysql/server/mysql/psi/psi_abi_v2.h
/usr/include/mysql/server/mysql/psi/psi_base.h
/usr/include/mysql/server/mysql/psi/psi_memory.h
/usr/include/mysql/server/mysql/service_base64.h
/usr/include/mysql/server/mysql/service_debug_sync.h
/usr/include/mysql/server/mysql/service_encryption.h
/usr/include/mysql/server/mysql/service_encryption_scheme.h
/usr/include/mysql/server/mysql/service_json.h
/usr/include/mysql/server/mysql/service_kill_statement.h
/usr/include/mysql/server/mysql/service_logger.h
/usr/include/mysql/server/mysql/service_md5.h
/usr/include/mysql/server/mysql/service_my_crypt.h
/usr/include/mysql/server/mysql/service_my_print_error.h
/usr/include/mysql/server/mysql/service_my_snprintf.h
/usr/include/mysql/server/mysql/service_progress_report.h
/usr/include/mysql/server/mysql/service_sha1.h
/usr/include/mysql/server/mysql/service_sha2.h
/usr/include/mysql/server/mysql/service_thd_alloc.h
/usr/include/mysql/server/mysql/service_thd_autoinc.h
/usr/include/mysql/server/mysql/service_thd_error_context.h
/usr/include/mysql/server/mysql/service_thd_mdl.h
/usr/include/mysql/server/mysql/service_thd_rnd.h
/usr/include/mysql/server/mysql/service_thd_specifics.h
/usr/include/mysql/server/mysql/service_thd_timezone.h
/usr/include/mysql/server/mysql/service_thd_wait.h
/usr/include/mysql/server/mysql/service_wsrep.h
/usr/include/mysql/server/mysql/services.h
/usr/include/mysql/server/mysql_com.h
/usr/include/mysql/server/mysql_com_server.h
/usr/include/mysql/server/mysql_embed.h
/usr/include/mysql/server/mysql_time.h
/usr/include/mysql/server/mysql_version.h
/usr/include/mysql/server/mysqld_ername.h
/usr/include/mysql/server/mysqld_error.h
/usr/include/mysql/server/pack.h
/usr/include/mysql/server/private/aria_backup.h
/usr/include/mysql/server/private/assume_aligned.h
/usr/include/mysql/server/private/atomic/gcc_builtins.h
/usr/include/mysql/server/private/atomic/generic-msvc.h
/usr/include/mysql/server/private/atomic/solaris.h
/usr/include/mysql/server/private/authors.h
/usr/include/mysql/server/private/backup.h
/usr/include/mysql/server/private/bounded_queue.h
/usr/include/mysql/server/private/client_settings.h
/usr/include/mysql/server/private/compat56.h
/usr/include/mysql/server/private/config.h
/usr/include/mysql/server/private/contributors.h
/usr/include/mysql/server/private/create_options.h
/usr/include/mysql/server/private/create_tmp_table.h
/usr/include/mysql/server/private/custom_conf.h
/usr/include/mysql/server/private/datadict.h
/usr/include/mysql/server/private/ddl_log.h
/usr/include/mysql/server/private/debug.h
/usr/include/mysql/server/private/debug_sync.h
/usr/include/mysql/server/private/derived_handler.h
/usr/include/mysql/server/private/derror.h
/usr/include/mysql/server/private/des_key_file.h
/usr/include/mysql/server/private/discover.h
/usr/include/mysql/server/private/dur_prop.h
/usr/include/mysql/server/private/embedded_priv.h
/usr/include/mysql/server/private/event_data_objects.h
/usr/include/mysql/server/private/event_db_repository.h
/usr/include/mysql/server/private/event_parse_data.h
/usr/include/mysql/server/private/event_queue.h
/usr/include/mysql/server/private/event_scheduler.h
/usr/include/mysql/server/private/events.h
/usr/include/mysql/server/private/field.h
/usr/include/mysql/server/private/field_comp.h
/usr/include/mysql/server/private/filesort.h
/usr/include/mysql/server/private/filesort_utils.h
/usr/include/mysql/server/private/ft_global.h
/usr/include/mysql/server/private/gcalc_slicescan.h
/usr/include/mysql/server/private/gcalc_tools.h
/usr/include/mysql/server/private/grant.h
/usr/include/mysql/server/private/group_by_handler.h
/usr/include/mysql/server/private/gstream.h
/usr/include/mysql/server/private/ha_partition.h
/usr/include/mysql/server/private/ha_sequence.h
/usr/include/mysql/server/private/handle_connections_win.h
/usr/include/mysql/server/private/handler.h
/usr/include/mysql/server/private/hash.h
/usr/include/mysql/server/private/hash_filo.h
/usr/include/mysql/server/private/heap.h
/usr/include/mysql/server/private/hostname.h
/usr/include/mysql/server/private/ilist.h
/usr/include/mysql/server/private/init.h
/usr/include/mysql/server/private/innodb_priv.h
/usr/include/mysql/server/private/item.h
/usr/include/mysql/server/private/item_cmpfunc.h
/usr/include/mysql/server/private/item_create.h
/usr/include/mysql/server/private/item_func.h
/usr/include/mysql/server/private/item_geofunc.h
/usr/include/mysql/server/private/item_jsonfunc.h
/usr/include/mysql/server/private/item_row.h
/usr/include/mysql/server/private/item_strfunc.h
/usr/include/mysql/server/private/item_subselect.h
/usr/include/mysql/server/private/item_sum.h
/usr/include/mysql/server/private/item_timefunc.h
/usr/include/mysql/server/private/item_vers.h
/usr/include/mysql/server/private/item_windowfunc.h
/usr/include/mysql/server/private/item_xmlfunc.h
/usr/include/mysql/server/private/json_table.h
/usr/include/mysql/server/private/key.h
/usr/include/mysql/server/private/keycaches.h
/usr/include/mysql/server/private/lex.h
/usr/include/mysql/server/private/lex_string.h
/usr/include/mysql/server/private/lex_symbol.h
/usr/include/mysql/server/private/lf.h
/usr/include/mysql/server/private/lock.h
/usr/include/mysql/server/private/log.h
/usr/include/mysql/server/private/log_event.h
/usr/include/mysql/server/private/log_event_old.h
/usr/include/mysql/server/private/log_slow.h
/usr/include/mysql/server/private/maria.h
/usr/include/mysql/server/private/mariadb.h
/usr/include/mysql/server/private/mdl.h
/usr/include/mysql/server/private/mem_root_array.h
/usr/include/mysql/server/private/message.h
/usr/include/mysql/server/private/multi_range_read.h
/usr/include/mysql/server/private/my_alarm.h
/usr/include/mysql/server/private/my_apc.h
/usr/include/mysql/server/private/my_atomic.h
/usr/include/mysql/server/private/my_atomic_wrapper.h
/usr/include/mysql/server/private/my_base.h
/usr/include/mysql/server/private/my_bit.h
/usr/include/mysql/server/private/my_bitmap.h
/usr/include/mysql/server/private/my_check_opt.h
/usr/include/mysql/server/private/my_compare.h
/usr/include/mysql/server/private/my_counter.h
/usr/include/mysql/server/private/my_cpu.h
/usr/include/mysql/server/private/my_crypt.h
/usr/include/mysql/server/private/my_decimal.h
/usr/include/mysql/server/private/my_default.h
/usr/include/mysql/server/private/my_handler_errors.h
/usr/include/mysql/server/private/my_json_writer.h
/usr/include/mysql/server/private/my_libwrap.h
/usr/include/mysql/server/private/my_md5.h
/usr/include/mysql/server/private/my_minidump.h
/usr/include/mysql/server/private/my_nosys.h
/usr/include/mysql/server/private/my_rdtsc.h
/usr/include/mysql/server/private/my_rnd.h
/usr/include/mysql/server/private/my_service_manager.h
/usr/include/mysql/server/private/my_stack_alloc.h
/usr/include/mysql/server/private/my_stacktrace.h
/usr/include/mysql/server/private/my_time.h
/usr/include/mysql/server/private/my_tree.h
/usr/include/mysql/server/private/my_uctype.h
/usr/include/mysql/server/private/my_user.h
/usr/include/mysql/server/private/myisam.h
/usr/include/mysql/server/private/myisamchk.h
/usr/include/mysql/server/private/myisammrg.h
/usr/include/mysql/server/private/myisampack.h
/usr/include/mysql/server/private/mysqld.h
/usr/include/mysql/server/private/mysqld_default_groups.h
/usr/include/mysql/server/private/mysqld_suffix.h
/usr/include/mysql/server/private/mysys_err.h
/usr/include/mysql/server/private/opt_range.h
/usr/include/mysql/server/private/opt_subselect.h
/usr/include/mysql/server/private/opt_trace.h
/usr/include/mysql/server/private/opt_trace_context.h
/usr/include/mysql/server/private/parse_file.h
/usr/include/mysql/server/private/partition_element.h
/usr/include/mysql/server/private/partition_info.h
/usr/include/mysql/server/private/password.h
/usr/include/mysql/server/private/pfs_file_provider.h
/usr/include/mysql/server/private/pfs_idle_provider.h
/usr/include/mysql/server/private/pfs_memory_provider.h
/usr/include/mysql/server/private/pfs_metadata_provider.h
/usr/include/mysql/server/private/pfs_socket_provider.h
/usr/include/mysql/server/private/pfs_stage_provider.h
/usr/include/mysql/server/private/pfs_statement_provider.h
/usr/include/mysql/server/private/pfs_table_provider.h
/usr/include/mysql/server/private/pfs_thread_provider.h
/usr/include/mysql/server/private/pfs_transaction_provider.h
/usr/include/mysql/server/private/privilege.h
/usr/include/mysql/server/private/probes_mysql.h
/usr/include/mysql/server/private/probes_mysql_nodtrace.h
/usr/include/mysql/server/private/procedure.h
/usr/include/mysql/server/private/protocol.h
/usr/include/mysql/server/private/proxy_protocol.h
/usr/include/mysql/server/private/queues.h
/usr/include/mysql/server/private/records.h
/usr/include/mysql/server/private/repl_failsafe.h
/usr/include/mysql/server/private/replication.h
/usr/include/mysql/server/private/rijndael.h
/usr/include/mysql/server/private/rowid_filter.h
/usr/include/mysql/server/private/rpl_constants.h
/usr/include/mysql/server/private/rpl_filter.h
/usr/include/mysql/server/private/rpl_gtid.h
/usr/include/mysql/server/private/rpl_injector.h
/usr/include/mysql/server/private/rpl_mi.h
/usr/include/mysql/server/private/rpl_parallel.h
/usr/include/mysql/server/private/rpl_record.h
/usr/include/mysql/server/private/rpl_record_old.h
/usr/include/mysql/server/private/rpl_reporting.h
/usr/include/mysql/server/private/rpl_rli.h
/usr/include/mysql/server/private/rpl_tblmap.h
/usr/include/mysql/server/private/rpl_utility.h
/usr/include/mysql/server/private/scheduler.h
/usr/include/mysql/server/private/scope.h
/usr/include/mysql/server/private/select_handler.h
/usr/include/mysql/server/private/semisync.h
/usr/include/mysql/server/private/semisync_master.h
/usr/include/mysql/server/private/semisync_master_ack_receiver.h
/usr/include/mysql/server/private/semisync_slave.h
/usr/include/mysql/server/private/service_versions.h
/usr/include/mysql/server/private/session_tracker.h
/usr/include/mysql/server/private/set_var.h
/usr/include/mysql/server/private/slave.h
/usr/include/mysql/server/private/source_revision.h
/usr/include/mysql/server/private/sp.h
/usr/include/mysql/server/private/sp_cache.h
/usr/include/mysql/server/private/sp_head.h
/usr/include/mysql/server/private/sp_pcontext.h
/usr/include/mysql/server/private/sp_rcontext.h
/usr/include/mysql/server/private/span.h
/usr/include/mysql/server/private/spatial.h
/usr/include/mysql/server/private/sql_acl.h
/usr/include/mysql/server/private/sql_admin.h
/usr/include/mysql/server/private/sql_alloc.h
/usr/include/mysql/server/private/sql_alter.h
/usr/include/mysql/server/private/sql_analyse.h
/usr/include/mysql/server/private/sql_analyze_stmt.h
/usr/include/mysql/server/private/sql_array.h
/usr/include/mysql/server/private/sql_audit.h
/usr/include/mysql/server/private/sql_base.h
/usr/include/mysql/server/private/sql_basic_types.h
/usr/include/mysql/server/private/sql_binlog.h
/usr/include/mysql/server/private/sql_bitmap.h
/usr/include/mysql/server/private/sql_bootstrap.h
/usr/include/mysql/server/private/sql_cache.h
/usr/include/mysql/server/private/sql_callback.h
/usr/include/mysql/server/private/sql_class.h
/usr/include/mysql/server/private/sql_cmd.h
/usr/include/mysql/server/private/sql_connect.h
/usr/include/mysql/server/private/sql_const.h
/usr/include/mysql/server/private/sql_crypt.h
/usr/include/mysql/server/private/sql_cte.h
/usr/include/mysql/server/private/sql_cursor.h
/usr/include/mysql/server/private/sql_db.h
/usr/include/mysql/server/private/sql_delete.h
/usr/include/mysql/server/private/sql_derived.h
/usr/include/mysql/server/private/sql_digest.h
/usr/include/mysql/server/private/sql_digest_stream.h
/usr/include/mysql/server/private/sql_do.h
/usr/include/mysql/server/private/sql_error.h
/usr/include/mysql/server/private/sql_explain.h
/usr/include/mysql/server/private/sql_expression_cache.h
/usr/include/mysql/server/private/sql_get_diagnostics.h
/usr/include/mysql/server/private/sql_handler.h
/usr/include/mysql/server/private/sql_help.h
/usr/include/mysql/server/private/sql_hset.h
/usr/include/mysql/server/private/sql_i_s.h
/usr/include/mysql/server/private/sql_insert.h
/usr/include/mysql/server/private/sql_join_cache.h
/usr/include/mysql/server/private/sql_lex.h
/usr/include/mysql/server/private/sql_lifo_buffer.h
/usr/include/mysql/server/private/sql_limit.h
/usr/include/mysql/server/private/sql_list.h
/usr/include/mysql/server/private/sql_load.h
/usr/include/mysql/server/private/sql_locale.h
/usr/include/mysql/server/private/sql_manager.h
/usr/include/mysql/server/private/sql_mode.h
/usr/include/mysql/server/private/sql_parse.h
/usr/include/mysql/server/private/sql_partition.h
/usr/include/mysql/server/private/sql_partition_admin.h
/usr/include/mysql/server/private/sql_plist.h
/usr/include/mysql/server/private/sql_plugin.h
/usr/include/mysql/server/private/sql_plugin_compat.h
/usr/include/mysql/server/private/sql_prepare.h
/usr/include/mysql/server/private/sql_priv.h
/usr/include/mysql/server/private/sql_profile.h
/usr/include/mysql/server/private/sql_reload.h
/usr/include/mysql/server/private/sql_rename.h
/usr/include/mysql/server/private/sql_repl.h
/usr/include/mysql/server/private/sql_schema.h
/usr/include/mysql/server/private/sql_select.h
/usr/include/mysql/server/private/sql_sequence.h
/usr/include/mysql/server/private/sql_servers.h
/usr/include/mysql/server/private/sql_show.h
/usr/include/mysql/server/private/sql_signal.h
/usr/include/mysql/server/private/sql_sort.h
/usr/include/mysql/server/private/sql_statistics.h
/usr/include/mysql/server/private/sql_string.h
/usr/include/mysql/server/private/sql_table.h
/usr/include/mysql/server/private/sql_tablespace.h
/usr/include/mysql/server/private/sql_test.h
/usr/include/mysql/server/private/sql_time.h
/usr/include/mysql/server/private/sql_trigger.h
/usr/include/mysql/server/private/sql_truncate.h
/usr/include/mysql/server/private/sql_tvc.h
/usr/include/mysql/server/private/sql_type.h
/usr/include/mysql/server/private/sql_type_geom.h
/usr/include/mysql/server/private/sql_type_int.h
/usr/include/mysql/server/private/sql_type_json.h
/usr/include/mysql/server/private/sql_type_real.h
/usr/include/mysql/server/private/sql_type_string.h
/usr/include/mysql/server/private/sql_udf.h
/usr/include/mysql/server/private/sql_union.h
/usr/include/mysql/server/private/sql_update.h
/usr/include/mysql/server/private/sql_view.h
/usr/include/mysql/server/private/sql_window.h
/usr/include/mysql/server/private/ssl_compat.h
/usr/include/mysql/server/private/strfunc.h
/usr/include/mysql/server/private/structs.h
/usr/include/mysql/server/private/sys_vars_shared.h
/usr/include/mysql/server/private/t_ctype.h
/usr/include/mysql/server/private/table.h
/usr/include/mysql/server/private/table_cache.h
/usr/include/mysql/server/private/thr_alarm.h
/usr/include/mysql/server/private/thr_lock.h
/usr/include/mysql/server/private/thr_malloc.h
/usr/include/mysql/server/private/thr_timer.h
/usr/include/mysql/server/private/thread_cache.h
/usr/include/mysql/server/private/threadpool.h
/usr/include/mysql/server/private/threadpool_generic.h
/usr/include/mysql/server/private/threadpool_winsockets.h
/usr/include/mysql/server/private/transaction.h
/usr/include/mysql/server/private/tzfile.h
/usr/include/mysql/server/private/tztime.h
/usr/include/mysql/server/private/uniques.h
/usr/include/mysql/server/private/unireg.h
/usr/include/mysql/server/private/vers_string.h
/usr/include/mysql/server/private/violite.h
/usr/include/mysql/server/private/waiting_threads.h
/usr/include/mysql/server/private/welcome_copyright_notice.h
/usr/include/mysql/server/private/win_tzname_data.h
/usr/include/mysql/server/private/winservice.h
/usr/include/mysql/server/private/wqueue.h
/usr/include/mysql/server/private/wsrep.h
/usr/include/mysql/server/private/wsrep_applier.h
/usr/include/mysql/server/private/wsrep_binlog.h
/usr/include/mysql/server/private/wsrep_client_service.h
/usr/include/mysql/server/private/wsrep_client_state.h
/usr/include/mysql/server/private/wsrep_condition_variable.h
/usr/include/mysql/server/private/wsrep_high_priority_service.h
/usr/include/mysql/server/private/wsrep_mutex.h
/usr/include/mysql/server/private/wsrep_mysqld.h
/usr/include/mysql/server/private/wsrep_mysqld_c.h
/usr/include/mysql/server/private/wsrep_priv.h
/usr/include/mysql/server/private/wsrep_schema.h
/usr/include/mysql/server/private/wsrep_server_service.h
/usr/include/mysql/server/private/wsrep_server_state.h
/usr/include/mysql/server/private/wsrep_sst.h
/usr/include/mysql/server/private/wsrep_storage_service.h
/usr/include/mysql/server/private/wsrep_thd.h
/usr/include/mysql/server/private/wsrep_trans_observer.h
/usr/include/mysql/server/private/wsrep_types.h
/usr/include/mysql/server/private/wsrep_utils.h
/usr/include/mysql/server/private/wsrep_var.h
/usr/include/mysql/server/private/wsrep_xid.h
/usr/include/mysql/server/private/xa.h
/usr/include/mysql/server/sql_common.h
/usr/include/mysql/server/sql_state.h
/usr/include/mysql/server/sslopt-case.h
/usr/include/mysql/server/sslopt-longopts.h
/usr/include/mysql/server/sslopt-vars.h
/usr/include/mysql/server/typelib.h
/usr/lib64/pkgconfig/libmariadb.pc
/usr/lib64/pkgconfig/mariadb.pc
/usr/share/man/man3/mariadb_cancel.3
/usr/share/man/man3/mariadb_connection.3
/usr/share/man/man3/mariadb_dyncol_check.3
/usr/share/man/man3/mariadb_dyncol_column_cmp_named.3
/usr/share/man/man3/mariadb_dyncol_column_count.3
/usr/share/man/man3/mariadb_dyncol_create_many_named.3
/usr/share/man/man3/mariadb_dyncol_create_many_num.3
/usr/share/man/man3/mariadb_dyncol_exists_named.3
/usr/share/man/man3/mariadb_dyncol_exists_num.3
/usr/share/man/man3/mariadb_dyncol_free.3
/usr/share/man/man3/mariadb_dyncol_list_named.3
/usr/share/man/man3/mariadb_dyncol_list_num.3
/usr/share/man/man3/mariadb_dyncol_unpack.3
/usr/share/man/man3/mariadb_dyncol_update_many_named.3
/usr/share/man/man3/mariadb_dyncol_update_many_num.3
/usr/share/man/man3/mariadb_get_infov.3
/usr/share/man/man3/mariadb_reconnect.3
/usr/share/man/man3/mariadb_rpl_close.3
/usr/share/man/man3/mariadb_rpl_fetch.3
/usr/share/man/man3/mariadb_rpl_get_optionsv.3
/usr/share/man/man3/mariadb_rpl_open.3
/usr/share/man/man3/mariadb_rpl_optionsv.3
/usr/share/man/man3/mariadb_stmt_execute_direct.3
/usr/share/man/man3/mariadb_stmt_fetch_fields.3
/usr/share/man/man3/mysql_affected_rows.3
/usr/share/man/man3/mysql_autocommit.3
/usr/share/man/man3/mysql_change_user.3
/usr/share/man/man3/mysql_close.3
/usr/share/man/man3/mysql_commit.3
/usr/share/man/man3/mysql_data_seek.3
/usr/share/man/man3/mysql_errno.3
/usr/share/man/man3/mysql_error.3
/usr/share/man/man3/mysql_fetch_field.3
/usr/share/man/man3/mysql_fetch_field_direct.3
/usr/share/man/man3/mysql_fetch_fields.3
/usr/share/man/man3/mysql_fetch_lengths.3
/usr/share/man/man3/mysql_fetch_row.3
/usr/share/man/man3/mysql_field_count.3
/usr/share/man/man3/mysql_field_seek.3
/usr/share/man/man3/mysql_field_tell.3
/usr/share/man/man3/mysql_free_result.3
/usr/share/man/man3/mysql_get_character_set_info.3
/usr/share/man/man3/mysql_get_client_info.3
/usr/share/man/man3/mysql_get_client_version.3
/usr/share/man/man3/mysql_get_host_info.3
/usr/share/man/man3/mysql_get_proto_info.3
/usr/share/man/man3/mysql_get_server_info.3
/usr/share/man/man3/mysql_get_server_version.3
/usr/share/man/man3/mysql_get_socket.3
/usr/share/man/man3/mysql_get_ssl_cipher.3
/usr/share/man/man3/mysql_hex_string.3
/usr/share/man/man3/mysql_info.3
/usr/share/man/man3/mysql_init.3
/usr/share/man/man3/mysql_kill.3
/usr/share/man/man3/mysql_more_results.3
/usr/share/man/man3/mysql_next_result.3
/usr/share/man/man3/mysql_num_fields.3
/usr/share/man/man3/mysql_num_rows.3
/usr/share/man/man3/mysql_options.3
/usr/share/man/man3/mysql_options4.3
/usr/share/man/man3/mysql_optionsv.3
/usr/share/man/man3/mysql_ping.3
/usr/share/man/man3/mysql_query.3
/usr/share/man/man3/mysql_read_query_result.3
/usr/share/man/man3/mysql_real_connect.3
/usr/share/man/man3/mysql_real_escape_string.3
/usr/share/man/man3/mysql_real_query.3
/usr/share/man/man3/mysql_refresh.3
/usr/share/man/man3/mysql_reset_connection.3
/usr/share/man/man3/mysql_rollback.3
/usr/share/man/man3/mysql_row_seek.3
/usr/share/man/man3/mysql_row_tell.3
/usr/share/man/man3/mysql_select_db.3
/usr/share/man/man3/mysql_send_query.3
/usr/share/man/man3/mysql_server_end.3
/usr/share/man/man3/mysql_server_init.3
/usr/share/man/man3/mysql_session_track_get_first.3
/usr/share/man/man3/mysql_session_track_get_next.3
/usr/share/man/man3/mysql_set_character_set.3
/usr/share/man/man3/mysql_set_server_option.3
/usr/share/man/man3/mysql_shutdown.3
/usr/share/man/man3/mysql_sqlstate.3
/usr/share/man/man3/mysql_ssl_set.3
/usr/share/man/man3/mysql_stat.3
/usr/share/man/man3/mysql_stmt_affected_rows.3
/usr/share/man/man3/mysql_stmt_attr_get.3
/usr/share/man/man3/mysql_stmt_attr_set.3
/usr/share/man/man3/mysql_stmt_bind_param.3
/usr/share/man/man3/mysql_stmt_bind_result.3
/usr/share/man/man3/mysql_stmt_close.3
/usr/share/man/man3/mysql_stmt_data_seek.3
/usr/share/man/man3/mysql_stmt_errno.3
/usr/share/man/man3/mysql_stmt_error.3
/usr/share/man/man3/mysql_stmt_execute.3
/usr/share/man/man3/mysql_stmt_fetch.3
/usr/share/man/man3/mysql_stmt_fetch_column.3
/usr/share/man/man3/mysql_stmt_field_count.3
/usr/share/man/man3/mysql_stmt_free_result.3
/usr/share/man/man3/mysql_stmt_init.3
/usr/share/man/man3/mysql_stmt_insert_id.3
/usr/share/man/man3/mysql_stmt_more_results.3
/usr/share/man/man3/mysql_stmt_next_result.3
/usr/share/man/man3/mysql_stmt_num_rows.3
/usr/share/man/man3/mysql_stmt_param_count.3
/usr/share/man/man3/mysql_stmt_param_metadata.3
/usr/share/man/man3/mysql_stmt_prepare.3
/usr/share/man/man3/mysql_stmt_reset.3
/usr/share/man/man3/mysql_stmt_result_metadata.3
/usr/share/man/man3/mysql_stmt_row_seek.3
/usr/share/man/man3/mysql_stmt_row_tell.3
/usr/share/man/man3/mysql_stmt_send_long_data.3
/usr/share/man/man3/mysql_stmt_sqlstate.3
/usr/share/man/man3/mysql_stmt_store_result.3
/usr/share/man/man3/mysql_stmt_warning_count.3
/usr/share/man/man3/mysql_store_result.3
/usr/share/man/man3/mysql_thread_end.3
/usr/share/man/man3/mysql_thread_id.3
/usr/share/man/man3/mysql_thread_init.3
/usr/share/man/man3/mysql_use_result.3
/usr/share/man/man3/mysql_warning_count.3

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/mariadb/*

%files extras
%defattr(-,root,root,-)
/usr/bin/mariadb-client-test-embedded
/usr/bin/mariadb-embedded
/usr/bin/mariadb-test-embedded
/usr/bin/mysql_client_test_embedded
/usr/bin/mysql_embedded
/usr/bin/mysqltest_embedded

%files extras-clientlib
%defattr(-,root,root,-)
/usr/lib64/libmariadb.so.3

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-mariadb

%files lib
%defattr(-,root,root,-)
/usr/lib64/glibc-hwcaps/x86-64-v3/libmariadb.so
/usr/lib64/glibc-hwcaps/x86-64-v3/libmariadb.so.3
/usr/lib64/glibc-hwcaps/x86-64-v3/libmariadbd.so
/usr/lib64/glibc-hwcaps/x86-64-v3/libmariadbd.so.19
/usr/lib64/glibc-hwcaps/x86-64-v3/libmysqlclient.so
/usr/lib64/glibc-hwcaps/x86-64-v3/libmysqlclient_r.so
/usr/lib64/glibc-hwcaps/x86-64-v3/libmysqld.so
/usr/lib64/libmariadb.so
/usr/lib64/libmariadbd.so
/usr/lib64/libmariadbd.so.19
/usr/lib64/libmysqlclient.so
/usr/lib64/libmysqlclient_r.so
/usr/lib64/libmysqld.so
/usr/lib64/mysql/plugin/adt_null.so
/usr/lib64/mysql/plugin/auth_0x0100.so
/usr/lib64/mysql/plugin/auth_ed25519.so
/usr/lib64/mysql/plugin/auth_pam.so
/usr/lib64/mysql/plugin/auth_pam_v1.so
/usr/lib64/mysql/plugin/auth_test_plugin.so
/usr/lib64/mysql/plugin/caching_sha2_password.so
/usr/lib64/mysql/plugin/client_ed25519.so
/usr/lib64/mysql/plugin/debug_key_management.so
/usr/lib64/mysql/plugin/dialog.so
/usr/lib64/mysql/plugin/dialog_examples.so
/usr/lib64/mysql/plugin/disks.so
/usr/lib64/mysql/plugin/example_key_management.so
/usr/lib64/mysql/plugin/file_key_management.so
/usr/lib64/mysql/plugin/func_test.so
/usr/lib64/mysql/plugin/ha_archive.so
/usr/lib64/mysql/plugin/ha_blackhole.so
/usr/lib64/mysql/plugin/ha_connect.so
/usr/lib64/mysql/plugin/ha_example.so
/usr/lib64/mysql/plugin/ha_federated.so
/usr/lib64/mysql/plugin/ha_federatedx.so
/usr/lib64/mysql/plugin/ha_rocksdb.so
/usr/lib64/mysql/plugin/ha_s3.so
/usr/lib64/mysql/plugin/ha_sphinx.so
/usr/lib64/mysql/plugin/ha_spider.so
/usr/lib64/mysql/plugin/ha_test_sql_discovery.so
/usr/lib64/mysql/plugin/handlersocket.so
/usr/lib64/mysql/plugin/libdaemon_example.so
/usr/lib64/mysql/plugin/locales.so
/usr/lib64/mysql/plugin/metadata_lock_info.so
/usr/lib64/mysql/plugin/mypluglib.so
/usr/lib64/mysql/plugin/mysql_clear_password.so
/usr/lib64/mysql/plugin/qa_auth_client.so
/usr/lib64/mysql/plugin/qa_auth_interface.so
/usr/lib64/mysql/plugin/qa_auth_server.so
/usr/lib64/mysql/plugin/query_cache_info.so
/usr/lib64/mysql/plugin/query_response_time.so
/usr/lib64/mysql/plugin/server_audit.so
/usr/lib64/mysql/plugin/sha256_password.so
/usr/lib64/mysql/plugin/simple_password_check.so
/usr/lib64/mysql/plugin/sql_errlog.so
/usr/lib64/mysql/plugin/test_sql_service.so
/usr/lib64/mysql/plugin/test_versioning.so
/usr/lib64/mysql/plugin/type_mysql_json.so
/usr/lib64/mysql/plugin/type_test.so
/usr/lib64/mysql/plugin/wsrep_info.so
/usr/lib64/security/pam_user_map.so
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mariadb/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/mariadb/040852207fc71d5144d9a73952f3c5b54003e89c
/usr/share/package-licenses/mariadb/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/mariadb/21c6e1c3c9ef7e68ec6cf63b3efda490e81ba26a
/usr/share/package-licenses/mariadb/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/mariadb/3914c2c16582bb3e404a22557a1f6b3c73db23a8
/usr/share/package-licenses/mariadb/420cc096d9ce8dfabee4082196acb0383377f202
/usr/share/package-licenses/mariadb/4231152540c27f86b02f96e73605e1ff18d2ee95
/usr/share/package-licenses/mariadb/46f1ac02159de45661948c23d007cf0ea989b459
/usr/share/package-licenses/mariadb/47aad6f6cae3514cdd9b80bb32587bf81d3b1fc0
/usr/share/package-licenses/mariadb/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/mariadb/59f297dcc2fbc8f9f3a966fd5290d72837fd6455
/usr/share/package-licenses/mariadb/5db84f12bde6c5e77125936e1470be0f400ece5f
/usr/share/package-licenses/mariadb/60d021148ab131e6640e0edd7801f12f02a384e1
/usr/share/package-licenses/mariadb/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1
/usr/share/package-licenses/mariadb/7907ce0c0a371f3efe022b224eeebf5898f2bf8c
/usr/share/package-licenses/mariadb/793d3cf202835b7b1584a2106d4292656d88e1ae
/usr/share/package-licenses/mariadb/7ef0f1c84d9b22a046df5af1de92f44837236897
/usr/share/package-licenses/mariadb/8065fd50693d562d8f14d53ca84db13df5280c47
/usr/share/package-licenses/mariadb/b3aebbdebf056cbf1cb73b76edf8ea105c37239d
/usr/share/package-licenses/mariadb/cdee1053a5302f5bd7ff2235a96d17c3c03ecd5c
/usr/share/package-licenses/mariadb/d4c4fe8d1effe5471779e799caaa09cbb54e5b3f
/usr/share/package-licenses/mariadb/ebebbb6bb4a431d7099e28f3fd1817a2bfdb1f72
/usr/share/package-licenses/mariadb/ff3ed70db4739b3c6747c7f624fe2bad70802987

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/aria_chk.1
/usr/share/man/man1/aria_dump_log.1
/usr/share/man/man1/aria_ftdump.1
/usr/share/man/man1/aria_pack.1
/usr/share/man/man1/aria_read_log.1
/usr/share/man/man1/aria_s3_copy.1
/usr/share/man/man1/galera_new_cluster.1
/usr/share/man/man1/galera_recovery.1
/usr/share/man/man1/innochecksum.1
/usr/share/man/man1/mariabackup.1
/usr/share/man/man1/mariadb-access.1
/usr/share/man/man1/mariadb-admin.1
/usr/share/man/man1/mariadb-backup.1
/usr/share/man/man1/mariadb-binlog.1
/usr/share/man/man1/mariadb-check.1
/usr/share/man/man1/mariadb-client-test-embedded.1
/usr/share/man/man1/mariadb-client-test.1
/usr/share/man/man1/mariadb-conv.1
/usr/share/man/man1/mariadb-convert-table-format.1
/usr/share/man/man1/mariadb-dump.1
/usr/share/man/man1/mariadb-dumpslow.1
/usr/share/man/man1/mariadb-embedded.1
/usr/share/man/man1/mariadb-find-rows.1
/usr/share/man/man1/mariadb-fix-extensions.1
/usr/share/man/man1/mariadb-hotcopy.1
/usr/share/man/man1/mariadb-import.1
/usr/share/man/man1/mariadb-install-db.1
/usr/share/man/man1/mariadb-ldb.1
/usr/share/man/man1/mariadb-plugin.1
/usr/share/man/man1/mariadb-secure-installation.1
/usr/share/man/man1/mariadb-service-convert.1
/usr/share/man/man1/mariadb-setpermission.1
/usr/share/man/man1/mariadb-show.1
/usr/share/man/man1/mariadb-slap.1
/usr/share/man/man1/mariadb-test-embedded.1
/usr/share/man/man1/mariadb-test.1
/usr/share/man/man1/mariadb-tzinfo-to-sql.1
/usr/share/man/man1/mariadb-upgrade.1
/usr/share/man/man1/mariadb-waitpid.1
/usr/share/man/man1/mariadb.1
/usr/share/man/man1/mariadb_config.1
/usr/share/man/man1/mariadbd-multi.1
/usr/share/man/man1/mariadbd-safe-helper.1
/usr/share/man/man1/mariadbd-safe.1
/usr/share/man/man1/mbstream.1
/usr/share/man/man1/msql2mysql.1
/usr/share/man/man1/my_print_defaults.1
/usr/share/man/man1/my_safe_process.1
/usr/share/man/man1/myisam_ftdump.1
/usr/share/man/man1/myisamchk.1
/usr/share/man/man1/myisamlog.1
/usr/share/man/man1/myisampack.1
/usr/share/man/man1/myrocks_hotbackup.1
/usr/share/man/man1/mysql-stress-test.pl.1
/usr/share/man/man1/mysql-test-run.pl.1
/usr/share/man/man1/mysql.1
/usr/share/man/man1/mysql.server.1
/usr/share/man/man1/mysql_client_test.1
/usr/share/man/man1/mysql_client_test_embedded.1
/usr/share/man/man1/mysql_config.1
/usr/share/man/man1/mysql_convert_table_format.1
/usr/share/man/man1/mysql_embedded.1
/usr/share/man/man1/mysql_find_rows.1
/usr/share/man/man1/mysql_fix_extensions.1
/usr/share/man/man1/mysql_install_db.1
/usr/share/man/man1/mysql_ldb.1
/usr/share/man/man1/mysql_plugin.1
/usr/share/man/man1/mysql_secure_installation.1
/usr/share/man/man1/mysql_setpermission.1
/usr/share/man/man1/mysql_tzinfo_to_sql.1
/usr/share/man/man1/mysql_upgrade.1
/usr/share/man/man1/mysql_waitpid.1
/usr/share/man/man1/mysqlaccess.1
/usr/share/man/man1/mysqladmin.1
/usr/share/man/man1/mysqlbinlog.1
/usr/share/man/man1/mysqlcheck.1
/usr/share/man/man1/mysqld_multi.1
/usr/share/man/man1/mysqld_safe.1
/usr/share/man/man1/mysqld_safe_helper.1
/usr/share/man/man1/mysqldump.1
/usr/share/man/man1/mysqldumpslow.1
/usr/share/man/man1/mysqlhotcopy.1
/usr/share/man/man1/mysqlimport.1
/usr/share/man/man1/mysqlshow.1
/usr/share/man/man1/mysqlslap.1
/usr/share/man/man1/mysqltest.1
/usr/share/man/man1/mysqltest_embedded.1
/usr/share/man/man1/mytop.1
/usr/share/man/man1/perror.1
/usr/share/man/man1/replace.1
/usr/share/man/man1/resolve_stack_dump.1
/usr/share/man/man1/resolveip.1
/usr/share/man/man1/wsrep_sst_common.1
/usr/share/man/man1/wsrep_sst_mariabackup.1
/usr/share/man/man1/wsrep_sst_mysqldump.1
/usr/share/man/man1/wsrep_sst_rsync.1
/usr/share/man/man1/wsrep_sst_rsync_wan.1
/usr/share/man/man8/mariadbd.8
/usr/share/man/man8/mysqld.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/mariadb-extra.socket
/usr/lib/systemd/system/mariadb-extra@.socket
/usr/lib/systemd/system/mariadb-install-db.service
/usr/lib/systemd/system/mariadb.service
/usr/lib/systemd/system/mariadb.socket
/usr/lib/systemd/system/mariadb@.service
/usr/lib/systemd/system/mariadb@.socket
/usr/lib/systemd/system/mariadb@bootstrap.service.d/use_galera_new_cluster.conf
/usr/lib/systemd/system/mysql.service
/usr/lib/systemd/system/mysqld.service
